### update record display

GET https://micro.loc/rest/edit/23 HTTP/1.1

### update record POST

POST https://micro.loc/rest/update/23 HTTP/1.1
Content-Type: multipart/form-data; boundary=----RESTVSCODE

------RESTVSCODE
Content-Disposition: form-data; name="text"

title
------RESTVSCODE
Content-Disposition: form-data; name="age"

23
------RESTVSCODE--