<?php

return [
	'rules folder' => '/rules/',
	'rules extension' => 'php',
	'filters folder' => '/filters/',
	'filters extension' => 'php',
	'rules' => [
		'alpha' => \projectorangebox\validate\rules\Alpha::class,
		'alpha_dash' => \projectorangebox\validate\rules\Alpha_dash::class,
		'alpha_numeric' => \projectorangebox\validate\rules\Alpha_numeric::class,
		'alpha_numeric_spaces' => \projectorangebox\validate\rules\Alpha_numeric_spaces::class,
		'alpha_space' => \projectorangebox\validate\rules\Alpha_space::class,
		'decimal' => \projectorangebox\validate\rules\Decimal::class,
		'differs' => \projectorangebox\validate\rules\Differs::class,
		'exact_length' => \projectorangebox\validate\rules\Exact_length::class,
		'greater_than' => \projectorangebox\validate\rules\Greater_than::class,
		'greater_than_equal_to' => \projectorangebox\validate\rules\Greater_than_equal_to::class,
		'if_empty' => \projectorangebox\validate\rules\If_empty::class,
		'in_list' => \projectorangebox\validate\rules\In_list::class,
		'integer' => \projectorangebox\validate\rules\Integer::class,
		'is_natural' => \projectorangebox\validate\rules\Is_natural::class,
		'is_natural_no_zero' => \projectorangebox\validate\rules\Is_natural_no_zero::class,
		'is_unique' => \projectorangebox\validate\rules\Is_unique::class,
		'is_uniquem' => \projectorangebox\validate\rules\Is_uniquem::class,
		'less_than' => \projectorangebox\validate\rules\Less_than::class,
		'less_than_equal_to' => \projectorangebox\validate\rules\Less_than_equal_to::class,
		'matches' => \projectorangebox\validate\rules\Matches::class,
		'max_length' => \projectorangebox\validate\rules\Max_length::class,
		'min_length' => \projectorangebox\validate\rules\Min_length::class,
		'numeric' => \projectorangebox\validate\rules\Numeric::class,
		'regex_match' => \projectorangebox\validate\rules\Regex_match::class,
		'required' => \projectorangebox\validate\rules\Required::class,
		'valid_base64' => \projectorangebox\validate\rules\Valid_base64::class,
		'valid_email' => \projectorangebox\validate\rules\Valid_email::class,
		'valid_emails' => \projectorangebox\validate\rules\Valid_emails::class,
		'valid_ip' => \projectorangebox\validate\rules\Valid_ip::class,
		'valid_url' => \projectorangebox\validate\rules\Valid_url::class,
	],
	'filters' => [
		'convert_date' => \projectorangebox\validate\filters\Convert_date::class,
		'filename' => \projectorangebox\validate\filters\Filename::class,
		'human' => \projectorangebox\validate\filters\Human::class,
		'input' => \projectorangebox\validate\filters\Input::class,
		'integer' => \projectorangebox\validate\filters\Integer::class,
		'length' => \projectorangebox\validate\filters\Length::class,
		'number' => \projectorangebox\validate\filters\Number::class,
		'slug' => \projectorangebox\validate\filters\Slug::class,
		'str' => \projectorangebox\validate\filters\Str::class,
		'textarea' => \projectorangebox\validate\filters\Textarea::class,
		'visible' => \projectorangebox\validate\filters\Visible::class,
	],
];
